doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                dbname:               '%db.mysql.dbname%'
                host:                 '%db.mysql.host%'
                port:                 '%db.mysql.port%'
                user:                 '%db.mysql.user%'
                password:             '%db.mysql.password%'
                driver:               'pdo_mysql'
                server_version:       '5.7'
                charset:              utf8mb4
                logging:              '%kernel.debug%'
                mapping_types:
                    enum: string
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
