version: "3.7"

services:

    nginx:
        image: nginx
        restart: on-failure
        networks:
            - some_black_magic
        volumes:
            - .:/app:delegated
            - .docker/nginx/conf/project.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${WEB_PORT:-80}:80

    php:
        image: ${DOCKER_SERVER_HOST}:${DOCKER_SERVER_PORT}/${DOCKER_PROJECT_PATH}/php${DOCKER_PHP_VERSION}-dev:${DOCKER_IMAGE_VERSION}
        user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
        restart: on-failure
        networks:
            - some_black_magic
        volumes:
            - .:/app:delegated
            - ~/.composer/cache:/home/app/.composer_cache:rw
#            - composer_home:/home/app/.composer

#volumes:
#    composer_home:

networks:
    some_black_magic:
        external: true
