apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          {{ if (.Values.image.tag) }}
          {{ if (.Values.image.env) }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}-nginx/{{ .Values.image.env }}:{{ .Values.image.tag }}"
          {{ end }}
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-nginx
        - name: {{ .Chart.Name }}-php
          {{ if (.Values.image.tag) }}
          {{ if (.Values.image.env) }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}-php/{{ .Values.image.env }}:{{ .Values.image.tag }}"
          {{ end }}
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-php
            - secretRef:
                name: {{ .Values.app.secretPrefix }}-generic